open module upupcat {
    requires transitive javafx.graphics;
    requires org.kordamp.ikonli.materialdesign;
    requires com.dlsc.workbenchfx.core;
    requires fr.brouillard.oss.cssfx;
    requires javafx.fxml;
    requires javafx.controls;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.ikonli.fontawesome;
    requires org.kordamp.ikonli.core;
    requires org.slf4j;
    requires com.calendarfx.view;
    //requires com.dlsc.gmapsfx;
    requires com.dlsc.preferencesfx;
    requires java.xml;
    requires com.google.common;
    requires javafx.web;
    requires java.logging;
    requires com.alibaba.fastjson2;
    requires com.github.oshi;
    requires org.apache.poi.poi;
    requires org.apache.poi.ooxml;
    //requires poi.ooxml;
    requires barcode4j;
    requires commons.lang;
    requires com.google.zxing;
    requires com.google.zxing.javase;
    requires org.apache.commons.io;
    requires transitive java.desktop;
    requires net.synedra.validatorfx;
    requires java.net.http;
    requires org.apache.commons.lang3;
    requires toml4j;
    requires barcodes;
    requires kernel;
    requires layout;    
    requires forms;
    requires io;   
    requires com.fazecast.jSerialComm;
	requires org.apache.pdfbox;
    requires com.cg.core.gui;
    requires com.google.gson;
	requires commons.beanutils;
	requires jdk.zipfs;
	requires com.dlsc.formsfx;
	requires javafx.base;
}
